Default: &defaults
  user: geekdarling2
  password: geekdarling2
  host: localhost
  port: 5432
  database: geekdarling2
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: geekdarling2_test
  <<: *defaults

Staging:
  database: geekdarling2_staging
  poolsize: 100
  <<: *defaults

Production:
  database: geekdarling2_production
  poolsize: 100
  <<: *defaults
