Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Copyright (c) o2s - OpenSourceSupport GmbH, 2014
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  port: 4000
  approot: "http://lambdad.o2s.ch:9000"
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
